name: Deploy to Mijndomein

on:
  push:
    branches:
      - main # Change this to the name of your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Mijndomein
        run: |
          cp -R * /httpdocs
        env:
          MY_DOMAIN_PASSWORD: ${{ secrets.MY_DOMAIN_PASSWORD }} # Add your Mijndomein password as a secret in your GitHub repository.
